### ISSUE TITLE
Badge code

### ISSUE THREAD

**Issue by aubertc** [erikmd/docker-coq-github-action-demo#15]
If I am not mistaken, the code to obtain a badge should be 

```
 [![Docker CI](https://github.com/$USER/$REPO/actions/workflows/build.yml/badge.svg)](https://github.com/$USER/$REPO/actions/workflows/build.yml) 
```

for a `build.yml` file, and not

https://github.com/erikmd/docker-coq-github-action-demo/blob/e5983192aa4410262408318779b48f43621c95a0/README.md?plain=1#L15-L17

**Comment by erikmd** [comment]
@aubertc I just seen your issue, belated thanks!

FYI: the current syntax for the markdown badge was not erroneous, it was the initially supported naming convention (essentially by filtering w.r.t. the workflows "names"), and the one you suggest was just later added.

But I agree it is better, as non-ambiguous, so I will change this now. Thanks.
